STATE_COLUMN = "A"
RECOVERY_COLUMN = "B"
MEMBER_COLUMN = "C"
AMT_COLUMN = {
  "NBFC": "D",
  "SBI": "E",
  "PRAYAAS":"F"
}
COLUMN_COLOR = {
  "B": "FFFFFF",
  "C": "C5E0B4",
  "D": "FFE699",
  "E": "9DC3E6",
  "F": "FFC000",
}

HEADER_ROW = 3
ROW_START = 4
COLUMN_WIDTH = 15